# Generated by Django 5.2.1 on 2026-02-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
